image: $IMAGE

stages:
  - version
  - publish

version:
 stage: version
 script:
  - 'release next-version --allow-current'
  - 'release next-version --allow-current > .next-version'
  - 'echo "RELEASE_SHA=$CI_COMMIT_SHA" > build_info'
  - 'echo "RELEASE_VERSION=$(cat .next-version)" >> build_info'
  - 'cat build_info'
  - '. build_info'
  - 'echo $RELEASE_VERSION'
 artifacts:
    paths:
      - build_info

publish_develop:
 stage: publish
 script:
  - '. build_info'
  - 'echo New version is: $RELEASE_VERSION'
  - export PREVIOUS_VERSION=$(jq -r '.version' package.json)
  - 'echo Previous version in package.json: $PREVIOUS_VERSION'
  - 'sed -i s/$PREVIOUS_VERSION/$RELEASE_VERSION/g package.json'
  - 'release changelog'
  - 'release commit-and-tag CHANGELOG.md build_info package.json'
  - 'npm-publish --token=$NPM_TOKEN --tag next'
 only:
  - develop
 when: manual

publish_main:
 stage: publish
 script:
  - '. build_info'
  - 'echo New version is: $RELEASE_VERSION'
  - export PREVIOUS_VERSION=$(jq -r '.version' package.json)
  - 'echo Previous version in package.json: $PREVIOUS_VERSION'
  - 'sed -i s/$PREVIOUS_VERSION/$RELEASE_VERSION/g package.json'
  - 'release changelog'
  - 'release commit-and-tag CHANGELOG.md build_info package.json'
  - 'npm-publish --token=$NPM_TOKEN'
 only:
  - main
 when: manual
