branch: master
publish: ['@semantic-release/gitlab', '@semantic-release/npm']
verifyConditions: ['@semantic-release/gitlab']
plugins: ['@semantic-release/commit-analyzer', '@semantic-release/release-notes-generator', '@semantic-release/gitlab', '@semantic-release/npm']